language: php

php:
  - 5.3
  - 5.5
  - 5.6
  - 7.0

env:
  global:
    - TYPO3_ORG_USERNAME=pagemachine
    - secure: CuQvdqN9vhydM34CX9fxddmSPe3tw7+W50jauZ79ZbHUyAgsVQdgrLCrfh9n6MX+vk4EVLJg8Fo5uSAcYDfwwXY7dWh7qrrerOcE9uBS0a4jWOrV/Xx6LEPBfM+C8TgbSVESK+LpJvCcXBMbXtyZrfnUoBgQPiRo8h7VaP2cHlo=
    - secure: Ia/9wpqHP+bdPGiJ0SS2IYptTh/o24b8mdq4lraUZbe6wGaeJUdtqXxB3foKLGSEJYmNmACpCGIQVLZw+L2JyxrtNI286m/V3JN8Z3sjT6KjONNSKFkUDRilFJ66qWhR25owY6nS14CRYgMT2myhFiaFRw79O/cyahenWW1SPZU=

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer config --global github-oauth.github.com "$GITHUB_OAUTH_TOKEN"

before_script:
  - composer install

script:
  - bin/parallel-lint --exclude bin --exclude vendor .

after_script:
  - >
    if [ -n "$TRAVIS_TAG" ]; then
      echo -e "Preparing upload of release ${TRAVIS_TAG} to TER\n"

      npm install
      npm wait

      if [ $? -eq 0 ]; then
        TAG_ANNOTATION="$(git tag -n -l $TRAVIS_TAG)"
        TAG_MESSAGE="${TAG_ANNOTATION#* }"

        git reset --hard
        git clean -xfd

        composer global require namelesscoder/typo3-repository-client:^1.1.1

        echo "Uploading release ${TRAVIS_TAG} to TER"
        upload . $TYPO3_ORG_USERNAME $TYPO3_ORG_PASSWORD "$TAG_MESSAGE"
      fi;
    fi;

notifications:
  slack:
    secure: TPgLYBAyIa6V6RT3YqndCnpkiifnY01ehmPrhVHU3G3yC4e4PtnqftgCrg8D4IBbmlVTxncNbsDqNbFfBEaJ1dMv6tv0yMpYlllfN5Syl3nBcjh43rHN4DWEffgJ59dAhJJtWjHvPfYR1/80EdKzsmepQl1i1+CXH1ryxtS6jEU=
