language: php

php:
  - 5.3

env:
  global:
    - TYPO3_ORG_USERNAME=pagemachine
    - secure: CuQvdqN9vhydM34CX9fxddmSPe3tw7+W50jauZ79ZbHUyAgsVQdgrLCrfh9n6MX+vk4EVLJg8Fo5uSAcYDfwwXY7dWh7qrrerOcE9uBS0a4jWOrV/Xx6LEPBfM+C8TgbSVESK+LpJvCcXBMbXtyZrfnUoBgQPiRo8h7VaP2cHlo=
    - secure: Ia/9wpqHP+bdPGiJ0SS2IYptTh/o24b8mdq4lraUZbe6wGaeJUdtqXxB3foKLGSEJYmNmACpCGIQVLZw+L2JyxrtNI286m/V3JN8Z3sjT6KjONNSKFkUDRilFJ66qWhR25owY6nS14CRYgMT2myhFiaFRw79O/cyahenWW1SPZU=

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer config --global github-oauth.github.com "$GITHUB_OAUTH_TOKEN"

before_script:
  - composer install

script:
  - find . -name \*.php ! -path "./bin/*" ! -path "./vendor*/" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;

after_script:
  - >
    if [ -n "$TRAVIS_TAG" ]; then
      echo "Preparing upload of release ${TRAVIS_TAG} to TER"
      echo;
      curl -sSL https://raw.githubusercontent.com/alrra/travis-after-all/1.3.0/lib/travis-after-all.js | node;
      if [ $? -eq 0 ]; then
        TAG_ANNOTATION="$(git tag -n -l $TRAVIS_TAG)"
        TAG_MESSAGE="${TAG_ANNOTATION#* }"
        echo "Uploading release ${TRAVIS_TAG} to TER"
        bin/upload . $TYPO3_ORG_USERNAME $TYPO3_ORG_PASSWORD "$TAG_MESSAGE"
      fi;
    fi;
  - >
