language: php
dist: trusty
sudo: false

cache:
  directories:
    - $HOME/.composer/cache

jobs:
  include:
    - stage: prepare
      script: composer self-update
    - stage: prepare
      php: 5.6
      script: composer install
    - stage: prepare
      php: 7.0
      script: composer install

    - stage: test
      script: bin/typoscript-lint
    - stage: test
      script: bin/xmllint --pattern "*.xlf*,svg" Resources
    - stage: test
      php: 5.6
      script: bin/parallel-lint --exclude bin --exclude vendor .
    - stage: test
      php: 7.0
      script: bin/parallel-lint --exclude bin --exclude vendor .
    - stage: test
      script: bin/phpcs

    - stage: deploy
      script: >
        if [ -n "$TRAVIS_TAG" ]; then
          echo -e "Preparing upload of release ${TRAVIS_TAG} to TER\n"

          if [ $? -eq 0 ]; then
            TAG_ANNOTATION="$(git tag -n -l $TRAVIS_TAG)"
            TAG_MESSAGE="${TAG_ANNOTATION#* }"

            git reset --hard
            git clean -xfd

            composer global require namelesscoder/typo3-repository-client:^1.1.1

            echo "Uploading release ${TRAVIS_TAG} to TER"
            $HOME/.composer/vendor/bin/upload . $TYPO3_ORG_USERNAME $TYPO3_ORG_PASSWORD "$TAG_MESSAGE"
          fi;
        fi;

notifications:
  slack:
    secure: TPgLYBAyIa6V6RT3YqndCnpkiifnY01ehmPrhVHU3G3yC4e4PtnqftgCrg8D4IBbmlVTxncNbsDqNbFfBEaJ1dMv6tv0yMpYlllfN5Syl3nBcjh43rHN4DWEffgJ59dAhJJtWjHvPfYR1/80EdKzsmepQl1i1+CXH1ryxtS6jEU=
